# Generated by Django 5.2.7 on 2025-10-29 02:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('cita', 'Cita Médica'), ('remedio', 'Toma de Remedio'), ('procedimiento', 'Procedimiento Médico'), ('otro', 'Otro')], max_length=20)),
                ('titulo', models.CharField(help_text='Ej: Cita con Dr. López, Tomar Paracetamol 500mg', max_length=200)),
                ('descripcion', models.TextField(blank=True, help_text='Detalles adicionales, indicaciones, etc.', null=True)),
                ('fecha_hora_evento', models.DateTimeField(help_text='Fecha y hora del evento médico.')),
                ('frecuencia_horas', models.PositiveIntegerField(blank=True, help_text='Para remedios, indicar cada cuántas horas tomar (ej: 8)', null=True)),
                ('recordatorio_cita_dias', models.CharField(blank=True, help_text="Días antes para recordar citas/procs (ej: '7,3,1')", max_length=50)),
                ('recordatorio_remedio_horas', models.PositiveIntegerField(default=1, help_text='Horas antes para recordar toma de remedio')),
                ('ultimo_recordatorio_enviado', models.DateTimeField(blank=True, editable=False, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_medicos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento Médico',
                'verbose_name_plural': 'Eventos Médicos',
                'ordering': ['fecha_hora_evento'],
            },
        ),
    ]
