# Generated by Django 5.2.8 on 2025-11-16 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventomedico',
            name='completado',
            field=models.BooleanField(default=False, help_text='Marcar si el evento fue completado por el usuario'),
        ),
    ]
