# Generated by Django 5.2.8 on 2025-11-16 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.PositiveIntegerField(blank=True, help_text='Tu edad actual', null=True)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=1, help_text='Tu peso actual en kilogramos (ej: 75.5)', max_digits=5, null=True)),
                ('condiciones_medicas', models.TextField(blank=True, help_text='Ej: Hipertensión, Diabetes tipo 2, Hipotiroidismo')),
                ('alergias', models.TextField(blank=True, help_text='Ej: Alergia a la Penicilina, Alergia al Polvo')),
                ('medicamentos_fijos', models.TextField(blank=True, help_text='Los medicamentos que tomas permanentemente. Ej: Losartán 50mg (1 al día), Eutirox 100mg (1 en ayunas)')),
                ('contactos_emergencia', models.TextField(blank=True, help_text='Ej: Juan Pérez (Hijo) - +56912345678, Dr. Silva (Médico) - +56987654321')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfilmedico', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
